In [2]:
import numpy as np

x = np.random.random()
print("Random number:", x)

Random number: 0.7156738209147789


In [3]:
x_square_root = np.sqrt(x)
print("Number square root:", x_square_root)
print('x^sqrt(x):', np.power(x, x_square_root))

Number square root: 0.8459750710953479
x^sqrt(x): 0.7535162503622329


In [4]:
matrix = np.random.random(3)
print('Random matrix:', matrix)

Random matrix: [0.14636284 0.4667285  0.38574854]


In [5]:
matrix = np.append(matrix, np.random.random(2))
print('New matrix:', matrix)

New matrix: [0.14636284 0.4667285  0.38574854 0.52145784 0.43394184]


In [6]:
print('Sine of matrix:', np.sin(matrix))

Sine of matrix: [0.14584084 0.4499671  0.37625278 0.49814475 0.42045055]


In [7]:
import numpy as np

mvalues = [0, 1, 5, 6, 80]
print(mvalues)
M = np.array(mvalues)
print('M =', M)

[0, 1, 5, 6, 80]
M = [ 0  1  5  6 80]


In [8]:
print(M * 39.3701) #convesion to inches

[   0.       39.3701  196.8505  236.2206 3149.608 ]


In [9]:
x = np.arange(20, 104.75, 3.6)
print(x)
x = np.linspace(20, 104.75, 10, endpoint=False)
print("x np.linspace=", x)

[ 20.   23.6  27.2  30.8  34.4  38.   41.6  45.2  48.8  52.4  56.   59.6
  63.2  66.8  70.4  74.   77.6  81.2  84.8  88.4  92.   95.6  99.2 102.8]
x np.linspace= [20.    28.475 36.95  45.425 53.9   62.375 70.85  79.325 87.8   96.275]


In [10]:
_,spacing = np.linspace(20, 104.75, 10, retstep=True) #returns spacing, don't want array right now
print('Spacing between the items in array above:', spacing)

Spacing between the items in array above: 9.416666666666666


In [12]:
x = np.array([1, 2, 3, 4])
print("x array:", x)
print('The type of x:', type(x))
print('The dimension of x:', np.ndim(x))

x array: [1 2 3 4]
The type of x: <class 'numpy.ndarray'>
The dimension of x: 1


In [13]:
x = np.array([ [[1, 2], [3, 4]],
             [[5, 6], [7, 8]],
             [[9, 10], [11, 12]] ]
)
print('3D array:')
print(x)

3D array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [14]:
print('number of dimensions:', x.ndim) #number of dimensions
print('Shape of array:', np.shape(x))

number of dimensions: 3
Shape of array: (3, 2, 2)


In [15]:
print('Sliced array:', x[1][1][0])

Sliced array: 7


In [16]:
x = np.arange(24).reshape(4,6) #Creates 4x6 array of elements from 0-23
print('x =')
print(x)

x =
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [17]:
print(x[::2, ::3]) #prints every 3rd item in every 2nd row

[[ 0  3]
 [12 15]]


In [18]:
z = np.zeros((3,5))
print('z=')
print(z)

i = np.identity(4)
print('i=')
print(i)

z=
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i=
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
print(np.eye(5, 8, k=1, dtype=int))


[[0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]


#k defines position of diagonal. If k=0, 
#we get ones on [0][0], [1],[1] etc... with k=1 we get them on [0][1], [1],[2]...
#So we get elements equal to 1 on [i][i+k] where i is row index, and all the other elements are set to 0

In [22]:
print(np.eye(5,8,k=0,dtype=int))

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]]


In [23]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [25]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [26]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


Can also use np.full((2,2), 7, np.double) or np.full((2,2),7,np.int)

In [27]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [28]:
e = np.random.random((2,2))
print(e)

[[0.42112873 0.32130895]
 [0.95672347 0.99775208]]


In [29]:
f = np.array([[1,2,3,4], [11,22,33,44], [111,222,333,444]])
print(f)

[[  1   2   3   4]
 [ 11  22  33  44]
 [111 222 333 444]]


Deviations

In [35]:
a = np.array([[1,2],[3,4]])
print('A matrix:')
print(a)

A matrix:
[[1 2]
 [3 4]]


In [36]:
print('Standard deviation=', np.std(a))

Standard deviation= 1.118033988749895


In [37]:
print('Standard deviation of rows=', np.std(a, axis=0))

Standard deviation of rows= [1. 1.]


In [38]:
print("Standard deviation of columns=", np.std(a, axis=1))

Standard deviation of columns= [0.5 0.5]


Eigen values

In [39]:
from numpy import linalg

a = np.diag((1,2,3))
print('A matrix:')
print(a)

A matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [40]:
eigenvalues,_ = linalg.eig(a)
print('Eigen values:')
print(eigenvalues)

Eigen values:
[1. 2. 3.]


In [45]:
b = np.array([[1,-1],[1,1]])
print('B matrix:')
print(b)

B matrix:
[[ 1 -1]
 [ 1  1]]


In [46]:
eigenvalues,_=linalg.eig(b)
print(eigenvalues)

[1.+1.j 1.-1.j]


Covariance

In [50]:
a = np.array([[1,2],[3,4]])
print('A matrix:')
print(a)

A matrix:
[[1 2]
 [3 4]]


In [51]:
print('Covariance=')
print(np.cov(a))

Covariance=
[[0.5 0.5]
 [0.5 0.5]]


In [52]:
def gauss(x, sigma):
    return np.exp(-x**2/(2*sigma**2))/(sigma*np.sqrt(2*np.pi))

In [55]:
G_matrix_1 = gauss(np.linspace(-5,5,10),1)
print(G_matrix_1)
G_matrix_2 = gauss(np.linspace(-5,5,10), 2)
print(G_matrix_2)
G_matrix = [[],[]]
G_matrix[0] = G_matrix_1
G_matrix[1] = G_matrix_2
print(G_matrix)
print('Covariance of two different gauss functions:')
print(np.cov(G_matrix))

[1.48671951e-06 2.07440309e-04 8.42153448e-03 9.94771388e-02
 3.41892294e-01 3.41892294e-01 9.94771388e-02 8.42153448e-03
 2.07440309e-04 1.48671951e-06]
[0.00876415 0.03012145 0.07603269 0.14095594 0.19192205 0.19192205
 0.14095594 0.07603269 0.03012145 0.00876415]
[array([1.48671951e-06, 2.07440309e-04, 8.42153448e-03, 9.94771388e-02,
       3.41892294e-01, 3.41892294e-01, 9.94771388e-02, 8.42153448e-03,
       2.07440309e-04, 1.48671951e-06]), array([0.00876415, 0.03012145, 0.07603269, 0.14095594, 0.19192205,
       0.19192205, 0.14095594, 0.07603269, 0.03012145, 0.00876415])]
Covariance of two different gauss functions:
[[0.01919045 0.00888522]
 [0.00888522 0.00519187]]


Project Determinants

In [56]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [57]:
print(np.linalg.det(a))

-2.0000000000000004


In [63]:
b = np.array([[[1,2],[3,4]],  [[1,2],[2,1]],[[1,3],[3,1]]])
print(b)
print(np.linalg.det(b))
c = np.array([[2,7],[8,4]])
print(c)
print(np.linalg.det(c))
print('det(A*C):', np.linalg.det(np.dot(a,c)))
print('det(A)*det(C):', np.linalg.det(a)*np.linalg.det(c))

[[[1 2]
  [3 4]]

 [[1 2]
  [2 1]]

 [[1 3]
  [3 1]]]
[-2. -3. -8.]
[[2 7]
 [8 4]]
-47.999999999999986
det(A*C): 95.99999999999999
det(A)*det(C): 95.99999999999999


Instructor mentions a name for one of the determinant methods. Sounds like bennet causchi, but not sure at all how to spell it. He says one takes less computing time